[program:inertia-ssr]
directory=/var/www/coffeepulseuganda
command=php artisan inertia:start-ssr --runtime=node
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/coffeepulseuganda/storage/logs/inertia-ssr.log
environment=PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
